import streamlit as st
from openai import OpenAI

# 1. Page Configuration
st.set_page_config(page_title="Nexora Studio Pro", page_icon="✨")
st.title("✨ Nexora Studio Pro")
st.markdown("#### *Created by Azkir - Next Gen AI*")

# 2. Direct Key Setup (Aapki key yahan laga di hai)
client = OpenAI(api_key="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")

# 3. User Input
prompt = st.text_area("Describe your image:", placeholder="e.g. A scary haunted house in the woods, 8k, cinematic...")

if st.button("Generate HD Image"):
    if prompt:
        with st.spinner("Azkir, DALL-E 3 aapki image bana raha hai..."):
            try:
                response = client.images.generate(
                    model="dall-e-3",
                    prompt=prompt,
                    size="1024x1024",
                    quality="hd",
                    n=1,
                )
                image_url = response.data[0].url
                st.image(image_url, caption="Generated by Nexora Studio", use_column_width=True)
                st.markdown(f'[📥 Download Image]({image_url})')
            except Exception as e:
                st.error(f"Error: {e}")
    else:
        st.warning("Pehle kuch likhen!")
