import streamlit as st
from openai import OpenAI

# 1. Page Configuration (Branding)
st.set_page_config(page_title="Nexora Studio", page_icon="✨", layout="centered")

# Branding for Azkir
st.title("✨ Nexora Studio Pro")
st.markdown("#### *Created by Azkir - Next Gen AI Image Generator*")
st.divider()

# 2. Secret Key Setup (Make sure to add 'OPENAI_API_KEY' in your secrets)
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

# 3. Sidebar for Settings
with st.sidebar:
    st.header("Settings")
    quality_mode = st.selectbox("Select Quality", ["Standard", "HD"])
    style_mode = st.radio("Style", ["Vivid (Bright)", "Natural (Realistic)"])

# 4. User Input
user_prompt = st.text_area("Describe your image (Prompt):", placeholder="e.g. A futuristic city in Pakistan with flying cars...")

if st.button("Generate HD Image"):
    if user_prompt:
        with st.spinner("Azkir, aapki image ban rahi hai... Please wait."):
            try:
                # 5. Image Generation with DALL-E 3 (High Quality)
                response = client.images.generate(
                    model="dall-e-3", # Ye line quality behtar karegi
                    prompt=user_prompt,
                    size="1024x1024",
                    quality=quality_mode.lower(), # User choice: Standard or HD
                    style=style_mode.lower(), # User choice: Vivid or Natural
                    n=1,
                )

                # 6. Display Result
                image_url = response.data[0].url
                st.image(image_url, caption="Generated by Nexora Studio", use_column_width=True)
                
                # Download Button
                st.markdown(f'<a href="{image_url}" download="Azkir_AI_Image.png">📥 Download Image</a>', unsafe_allow_html=True)

            except Exception as e:
                st.error(f"Oh! Aik error aa gaya: {e}")
    else:
        st.warning("Pehle kuch likh to dein!")

st.divider()
st.info("Tip: Detail wala prompt likhein jaise 'Cinematic lighting, 8k, hyper-realistic' behtareen results ke liye.")
