import streamlit as st
import requests
import io
from PIL import Image

# 1. Page Setup
st.set_page_config(page_title="Nexora Studio Pro", page_icon="✨")
st.title("✨ Nexora Studio Pro")
st.markdown("#### *Created by Azkir - Free HD Image Generator*")

# 2. Hugging Face Setup (Free Token)
API_URL = "https://api-inference.huggingface.co/models/black-forest-labs/FLUX.1-schnell"
headers = {"Authorization": "Bearer Hf_XGACBqHcVSSVLkggPBgFttejhIykbDFaJq"}

def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.content

# 3. User Interface
prompt = st.text_area("Describe your image:", placeholder="Azkir, apna idea yahan likhein (English mein)...")

if st.button("Generate HD Image"):
    if prompt:
        with st.spinner("Azkir, tasveer ban rahi hai..."):
            try:
                image_bytes = query({"inputs": prompt})
                image = Image.open(io.BytesIO(image_bytes))
                st.image(image, caption="Generated by Nexora Studio", use_column_width=True)
                
                # Download Button
                buf = io.BytesIO()
                image.save(buf, format="PNG")
                st.download_button("📥 Download Image", data=buf.getvalue(), file_name="azkir_image.png", mime="image/png")
            except:
                st.error("Model abhi thora busy hai, ek baar phir button dabayein!")
    else:
        st.warning("Pehle kuch likhen!")
